/**
 * This is an automatically generated file. Contents are not allowed to be changed - they might be overwritten. 
 * 
 * Generated by the Homevoice.io Code Plugin
 */
@FilterDef(name="filterDeleted", defaultCondition="deleted_at IS NULL")
package org.acme.persistence;

import org.hibernate.annotations.FilterDef;